name: Dev Release & Auto-Tag

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
 
  create-dev-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      new_tag: ${{ steps.versioning.outputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      # --- RUN TESTS
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-node_modules-
      
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run test
        run: npm run test:cov     

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      # --- NOVO STEP: PRINT DA ÚLTIMA TAG ---
      - name: Show Previous Tag
        # Tenta pegar a última tag (suprimindo erros caso não exista nenhuma)
        # '2>/dev/null' esconde mensagens de erro do git se for um repo novo
        # '||' define um valor padrão caso falhe
        run: |
          echo "Buscando última tag existente no repositório..."

          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "Nenhuma tag encontrada (Primeira execução?)")
          
          echo "=============================================="
          echo "  ÚLTIMA TAG ENCONTRADA: $LAST_TAG"
          echo "=============================================="

      - name: Generate Dev version & tag
        id: versioning

        # Gera uma versão prerelease (ex: 1.2.3-DEV.0)
        # O --no-git-tag-version evita que o npm crie a tag git automaticamente, queremos controlar isso
        # Pega a versão atualizada do package.json
        # Cria a tag no Git e sobe
        # Exporta para os próximos jobs

        # ======================================
        # VERSSAO ANTERIOR
        # AJUSTAR A TAG PARA SER COMPATIVEL COM A VERSÃO DO PACKAGE.JSON
        run: |
          echo "=========================================="
          echo "GERANDO TAG DE DEV"
          echo "=========================================="
          
          # 1. Pega a versão crua do arquivo
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE VERSION: $PKG_VERSION"
          
          # 2. Formata a Tag (Garante o padrão vX.Y.Z-DEV)
          # Remove o sufixo -DEV caso o dev já tenha colocado no package.json, para evitar duplicação
          BASE_VERSION=$(echo $PKG_VERSION | sed 's/-DEV//')
          
          # Adiciona o padrão v...-DEV
          TARGET_TAG="v${BASE_VERSION}-DEV"
          echo "Tag Alvo para criação: $TARGET_TAG"
          
          echo "------------------------------------------"
          
          # 3. VALIDAÇÃO DE EXISTÊNCIA (O ponto chave)
          if git rev-parse "$TARGET_TAG" >/dev/null 2>&1; then
            echo "ERRO CRÍTICO: A tag '$TARGET_TAG' JÁ EXISTE no repositório."
            echo "MOTIVO: A versão no package.json ($PKG_VERSION) não foi alterada desde o último release."
            echo "AÇÃO NECESSÁRIA: Atualize o package.json (ex: 1.0.1 -> 1.0.2) e faça um novo push."
            exit 1 # Quebra o workflow aqui
          else
            echo "Criando tag '$TARGET_TAG' .... "
          fi
          
          echo "------------------------------------------"
          
          # 4. Criação da Tag (Se chegou aqui, é seguro)
          # O package.json não precisa ser alterado (npm version) pois já lemos dele
          
          git tag $TARGET_TAG
          git push origin $TARGET_TAG
          
          echo "🎉 Tag $TARGET_TAG criada e enviada com sucesso!"
          
          # 5. Exporta para o próximo job
          echo "version=$TARGET_TAG" >> $GITHUB_OUTPUT

  # -- REDUNDANT DESNECESSARIO --
  # run-tests:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps: 
  #     - name: Checkout code
  #       uses: actions/checkout@v4
    
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         registry-url: 'https://registry.npmjs.org'

  #     - name: Cache node_modules
  #       uses: actions/cache@v4
  #       id: node_modules_cache
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #          ${{ runner.os }}-node_modules-
      
  #     - name: Install dependencies
  #       if: steps.node_modules_cache.outputs.cache-hit != 'true'
  #       run: npm ci

  #     - name: Run test
  #       run: npm run test
  #       run: npm run test:cov

